### ISSUE TITLE
Hide desktop mirroring

### ISSUE THREAD

**Issue by Codesterz** [mosirnik/KK_MainGameVR#44]
This really needs an option to hide the desktop screen mirroring.

**Comment by mosirnik** [comment]
The window needs to be there for simulated mouse clicks to work. It shouldn't be too hard to turn it into a completely black window, though.

Why do you want this?

**Comment by Codesterz** [comment]
If someone enters my room while I'm playing I don't want them to see the game.

**Comment by mosirnik** [comment]
That's fair, I'll implement it.

**Comment by mosirnik** [comment]
[KK_MainGameVR-0.12.1-51876.zip](https://github.com/mosirnik/KK_MainGameVR/files/7000678/KK_MainGameVR-0.12.1-51876.zip)

OK I implemented this. Can you give it a try? Enable the "Privacy screen" option in the config.

**Comment by mosirnik** [comment]
I believe this is fixed.

@Codesterz Feel free to open another issue if the feature doesn't work.
