### ISSUE TITLE
Binding for "secondary" button.

### ISSUE THREAD

**Issue by Secmess** [mosirnik/KK_MainGameVR#53]
In the Plugin Setting, you will see that there's a toggle to enable secondary assignment, and a separate binding for them.

How do you enable them? At first I thought it meant my left & right controller would have different binding, but they're both the same.

I can testify that it's actually recognized because there's a number in my binding now, `1`, but no way to switch them.

**Comment by mosirnik** [comment]
You can assign "Switch button assignments" to one of your buttons.

Admittedly this is cumbersome and not really intuitive either.
